### PR TITLE
Scoped Approval

### PR DESCRIPTION
**Pull request by ericbinet**
Added scoped approval to the standard.

### CODE REVIEW

**Comment by coinfork** [comment]
Is the URI in printf format? Shouldn't this be %s.json ?
    "uri": "ipfs://QmPvaEQFVvuiaYzkSVUp23iHTQeEUpDaJnP8U7C3PqE57w/%l.json",

**Comment by ericbinet** [comment]
> Is the URI in printf format? Shouldn't this be %s.json ?
> "uri": "ipfs://QmPvaEQFVvuiaYzkSVUp23iHTQeEUpDaJnP8U7C3PqE57w/%l.json",

This URI didn't use %s, I'll change it to something that does.

**Comment by ericbinet** [comment]
The fact is, `%s` is optional, I didn't see a need to use it.

**Comment by JamesTherien** [comment]
There should be an event on ScopeURI set.

**Comment by JamesTherien** [comment]
event ScopeURI(string _value, uint256 indexed _scope) -> scope should be bytes32.

**Comment by JamesTherien** [comment]
Can we have getScopeCountForId() public instead of external. There is no difference in perf in this case, and it can be useful for internal implementation.

**Comment by ericbinet** [comment]
> Can we have getScopeCountForId() public instead of external. There is no difference in perf in this case, and it can be useful for internal implementation.

I could make all view functions public to make them usable within the contract.

**Comment by JamesTherien** [comment]
Looking at the scope approval api, it would be nice to be more consistant with the core standard naming:
getScopeUri -> scopeUri 
getScopeForId -> scopeForId
getScopeCountForId -> scopeCountForId

**Comment by ericbinet** [comment]
Good catch. I will update the spec.

**Pull request merged**
